"""
Sources API — YOU implement the handler logic.

Endpoints:
  POST /sources       — Create a new webhook source, return it with the inbound token
  GET  /sources/{id}/events — List all events received by this source
"""
import uuid

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.source import Source
from app.models.event import Event
from datetime import datetime

router = APIRouter()


# --- Pydantic schemas for request/response ---

class SourceCreate(BaseModel):
    name: str


class SourceResponse(BaseModel):
    id: uuid.UUID
    name: str
    token: str
    inbound_url: str  # Build this from the token: f"/in/{token}"
    created_at: datetime

    model_config = {"from_attributes": True}


class EventResponse(BaseModel):
    id: uuid.UUID
    source_id: uuid.UUID
    headers: dict
    body: dict | None
    query_params: dict
    status: str
    received_at: datetime

    model_config = {"from_attributes": True}


# --- YOUR WORK STARTS HERE ---

@router.post("", status_code=201)
async def create_source(payload: SourceCreate, db: AsyncSession = Depends(get_db)):
    """
    TODO — Implement this yourself:
    1. Create a new Source row using the name from the payload
    2. The token is auto-generated by the model default
    3. Add it to the session, flush to get the ID
    4. Return a SourceResponse with all fields filled in
       - Build inbound_url as f"/in/{source.token}"
       - Convert created_at to ISO string
    """
    new_source = Source(name = payload.name)
    db.add(new_source)
    await db.flush()
    return SourceResponse(id = new_source.id, name = new_source.name, token= new_source.token, inbound_url=f"/in/{new_source.token}", created_at=new_source.created_at)



@router.get("/{source_id}/events")
async def list_events(source_id: uuid.UUID, db: AsyncSession = Depends(get_db)):
    """
    TODO — Implement this yourself:
    1. Verify the source exists (return 404 if not)
    2. Query all Events where source_id matches, ordered by received_at desc
    3. Return a list of EventResponse objects
    """
    match = await db.execute(select(Source).where(Source.id == source_id))
    check = match.scalar_one_or_none()
    if check is None:
        raise HTTPException(404)
    query = await db.execute(select(Event).where(Event.source_id == source_id).order_by(Event.received_at.desc()))
    final_query = query.scalars().all()
    events = []
    for e in final_query:
        events.append(EventResponse(id = e.id, source_id= e.source_id, headers = e.headers, body = e.body, query_params= e.query_params, status= e.status, received_at= e.received_at))
    return(events)
